"""contracts —— 三人共同拥有，Day 1 冻结的跨模块契约。

跨模块通信只通过这里的 schema / 枚举，不引用对方内部对象。
"""

# 冻结契约版本戳：盖进 RunConfigSnapshot / run 记录，支撑跨版本复现与对比。
# 改动契约（走 README §4）时 bump 此值，并在 §7 记一行。
CONTRACT_VERSION = "2.2"

from contracts.enums import (
    ActionType,
    AgentVersion,
    Camp,
    ClaimedAlignment,
    DeathCause,
    DeviationOutcome,
    EventType,
    FailureCategory,
    Phase,
    PlayerStatus,
    Role,
    Visibility,
    VisibilityLevel,
)
from contracts.schemas import (
    AgentAction,
    AgentContext,
    AgentDecisionTrace,
    AgentTuningTrace,
    BadCaseReport,
    BatchRunReport,
    BeliefCurvePoint,
    BeliefState,
    BeliefUpdateBatch,
    BeliefUpdateDelta,
    ClaimRecord,
    ClaimResult,
    ContextBudgetConfig,
    ContextSnapshot,
    ContractModel,
    CreateGameResponse,
    DecisionQualityFlags,
    Deviation,
    DeviationEvent,
    EvaluationReport,
    EvidenceEvent,
    FactStreamSummary,
    FewShotCase,
    GameConfig,
    GameEvent,
    GameRules,
    GameRunResult,
    HunterState,
    KeyTurningPoint,
    LeaderboardResponse,
    LeaderboardRow,
    ModelConfig,
    NightState,
    OutcomeAttribution,
    PerAgentMetric,
    PlayerFactSummary,
    PlayerState,
    PromptChange,
    PromptVersion,
    PublicEvent,
    PrivateEvent,
    ReplayData,
    ReplayPlayer,
    RoleBelief,
    RoleCounts,
    RoundState,
    RunConfigSnapshot,
    RunGameResponse,
    RunStatus,
    StepGameResponse,
    StrategyMemoryItem,
    Timing,
    TruthState,
    VisiblePlayer,
    VoteRecord,
    WitchState,
)

__all__ = [
    "CONTRACT_VERSION",
    # enums
    "ActionType",
    "AgentVersion",
    "Camp",
    "ClaimedAlignment",
    "DeathCause",
    "DeviationOutcome",
    "EventType",
    "FailureCategory",
    "Phase",
    "PlayerStatus",
    "Role",
    "Visibility",
    "VisibilityLevel",
    # schemas
    "ContractModel",
    "ClaimResult",
    "Timing",
    "Deviation",
    "RoleCounts",
    "ModelConfig",
    "GameRules",
    "GameConfig",
    "PlayerState",
    "WitchState",
    "HunterState",
    "NightState",
    "RoundState",
    "TruthState",
    "VisiblePlayer",
    "PublicEvent",
    "PrivateEvent",
    "GameEvent",
    "ClaimRecord",
    "VoteRecord",
    "AgentContext",
    "AgentAction",
    "RoleBelief",
    "BeliefState",
    "DeviationEvent",
    "ContextBudgetConfig",
    "FactStreamSummary",
    "PlayerFactSummary",
    "StrategyMemoryItem",
    "FewShotCase",
    "PromptVersion",
    "AgentDecisionTrace",
    "EvidenceEvent",
    "BadCaseReport",
    "PromptChange",
    "AgentTuningTrace",
    "PerAgentMetric",
    "KeyTurningPoint",
    "EvaluationReport",
    "LeaderboardRow",
    "ReplayData",
    "CreateGameResponse",
    "StepGameResponse",
    "RunGameResponse",
    "LeaderboardResponse",
    # v2.2 预留（9P + Observability + Learning）
    "ReplayPlayer",
    "ContextSnapshot",
    "BeliefUpdateDelta",
    "BeliefUpdateBatch",
    "BeliefCurvePoint",
    "DecisionQualityFlags",
    "OutcomeAttribution",
    "RunConfigSnapshot",
    "GameRunResult",
    "BatchRunReport",
    "RunStatus",
]
